//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventDetails
    {
        public int IdDose { get; set; }
        public int IdMenu { get; set; }
        public int amount { get; set; }
        public int Id { get; set; }
    
        public virtual InventDose InventDose { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
