//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VipTables
    {
        public int Id { get; set; }
        public Nullable<int> IdTable { get; set; }
        public Nullable<int> IdVisiter { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> DateTimeStart { get; set; }
        public Nullable<int> IdServing { get; set; }
        public string CountPeople { get; set; }
    
        public virtual CurrentEmployee CurrentEmployee { get; set; }
        public virtual CurrentEmployee CurrentEmployee1 { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
